version: '3'
services:
  db:
    image: mysql:8.0.33-debian
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: shop
    restart: always

  backend:
    image: ${DOCKERHUB_USERNAME}/backend:${BACKEND_IMAGE_TAG}
    container_name: backend
    ports:
      - "8080:8080"
    volumes:
      - ${VM_LOGS_PATH}:/app/logs
      - ${VM_IMAGES_PATH}:/app/images
    networks:
      - app-network
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_URL: ${DB_URL}
      WAIT_HOSTS: db:3306
      SPRING_PROFILES_ACTIVE: dev-remote-VM
    restart: always

  frontend:
    image: ${DOCKERHUB_USERNAME}/frontend:${FRONTEND_IMAGE_TAG}
    container_name: frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${VM_LOGS_PATH}:/app/logs
      - ${VM_IMAGES_PATH}:/app/images
      - cert-data:/etc/letsencrypt:ro
      - html-data:/var/www/certbot
    networks:
      - app-network
    depends_on:
      - backend


  certbot:
    image: certbot/certbot
    volumes:
      - cert-data:/etc/letsencrypt
      - html-data:/var/www/certbot
      - cert-log:/var/log/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --webroot --webroot-path=/var/www/certbot && sleep 12h & wait $${!}; done;'"
    networks:
      - app-network
    depends_on:
      - frontend


networks:
  app-network:
    driver: bridge

volumes:
  db-data:
  cert-data:
  cert-log:
  html-data:

